apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapp
spec:
  selector:
    matchLabels:
      app: basicapp
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      containers:
      - name: basicapp
        command: ["/bin/bash", "-ec", "bundle exec rails db:migrate RAILS_ENV=development && bundle exec puma"]
        image: {{ .Values.werf.image.basicapp }}
        ports:
        - containerPort: 3000
        env:
        - name: "SQLITE_FILE"
          value: "app.db"
