company_name: Flant
company_url: https://flant.ru
url: https://werf.io
site_lang: en
editlink: "https://github.com/werf/werf-guides/edit/master/werf.io/guides"
issuelink: "https://github.com/werf/werf-guides/issues/new"
docsurl: https://werf.io
includes_dir: _includes/en

breadcrumbs:
  hometext: "Home"

exclude:
  - Gemfile
  - Gemfile.lock
  - examples
  - pages_ru
  - ru.werf.io # TODO: remove

include:
  - pages_en
  - werf.io # TODO: remove

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: en
      comments: true
      search: true
      sidebar: sidebar
      topnav: topnav
      sitemap_include: true
      multilang: false
  - scope:
      path: "nodejs"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: nodejs
      toc: false
      label_ci: GitLab
      label_framework: "Node.js"
      multilang: true
  - scope:
      path: "java_springboot"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: java_springboot
      toc: false
      label_ci: GitLab
      label_framework: "Spring Boot"
      multilang: true
  - scope:
      path: "python_django"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: python_django
      toc: false
      label_ci: GitLab
      label_framework: Django
  - scope:
      path: "rails"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: rails
      toc: false
      label_ci: GitLab
      label_framework: Rails