company_name: Флант
company_url: https://flant.ru
url: https://ru.werf.io
site_lang: ru
editlink: "https://github.com/werf/werf-guides/edit/master/ru.werf.io/guides"
issuelink: "https://github.com/werf/werf-guides/issues/new"
docsurl: https://ru.werf.io
includes_dir: _includes/ru

breadcrumbs:
  hometext: "Начало"

exclude:
  - Gemfile
  - Gemfile.lock
  - examples
  - pages_en
  - werf.io # TODO: remove

include:
  - pages_ru
  - ru.werf.io # TODO: remove

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: ru
      comments: true
      search: true
      sidebar: sidebar
      topnav: topnav
      multilang: false
      sitemap_include: true
  - scope:
      path: "nodejs"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: nodejs
      framework_name: "Node.js"
      toc: false
      multilang: true
  - scope:
      path: "java_springboot"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: java_springboot
      framework_name: "Spring Boot"
      toc: false
      multilang: true
  - scope:
      path: "django"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: django
      framework_name: Django
      toc: false
  - scope:
      path: "golang"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: golang
      framework_name: Go
      toc: false
  - scope:
      path: "rails"
      type: "pages"
    values:
      sidebar: applications_guide_nav
      framework_id: rails
      framework_name: Rails
      toc: false
