company_name: Флант
company_url: https://flant.ru
url: https://ru.werf.io
site_lang: ru
baseurl: /applications_guide_ru

exclude:
- applications_guide_en/

include:
- applications_guide_ru/

breadcrumbs:
  hometext: "Начало"

