output: web

topnav_title: werf
site_title: werf
site_urls:
  ru: https://ru.werf.io
  en: https://werf.io

social_links:
  ru:
    twitter: https://twitter.com/werf_io
    telegram: https://t.me/werf_ru
    slack_1: https://slack.cncf.io/
    slack_2: https://cloud-native.slack.com/messages/CHY2THYUU
  en:
    twitter: https://twitter.com/werf_io
    slack_1: https://slack.cncf.io/
    slack_2: https://cloud-native.slack.com/messages/CHY2THYUU

exclude:
- .idea/
- .gitignore
- vendor

highlighter: rouge

plugins:
- jekyll-assets

markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
  hometext: "Home"

collections:
  tooltips:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: en
      comments: true
      search: true
      sidebar: sidebar
      topnav: topnav
      sitemap_include: true
      multilang: true
  - scope:
      path: "applications_guide_ru"
      type: "pages"
    values:
      lang: ru


sidebars:
- documentation

