apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watch-resources
rules:
- apiGroups:
  - batch
  - apps
  resources:
  - jobs
  - statefulsets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watch-resources
subjects:
- kind: ServiceAccount
  name: default
