production:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: mysql
  port: 3306
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: werf-guide-app
  encoding: utf8
