minio:
  service: S3
  endpoint: http://minio:9000
  region: us-east-1
  bucket: werf-guide-app
  access_key_id: <%= ENV["S3_USERNAME"] %>
  secret_access_key: <%= ENV["S3_PASSWORD"] %>
  force_path_style: true
