name: Cleanup Docker registry
on:
  schedule:
    - cron:  '0 6 * * *'
  repository_dispatch:
    types: [cleanup]

env:
  WERF_ENV: "production"
  WERF_REPO: "registry.flant.com/werf/werf-werf-guides"

jobs:
  cleanup:
    name: Cleanup
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Log in to the registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.WERF_REPO }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_CLEANUP_TOKEN }}

      - name: Cleanup
        uses: werf/actions/cleanup@v1.2
        env:
          WERF_LOG_VERBOSE: "on"
