name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types: [ labeled, synchronize ]

env:
  WERF_ENV: "production"
  WERF_REPO: "registry.flant.com/werf/werf-werf-guides"

jobs:
  converge:
    name: Deploy
    if: github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'test guides')
    runs-on: self-hosted
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Log in to the registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.WERF_REPO }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Deploy to test
      uses: werf/actions/converge@v1.2
      with:
        env: test
      env:
        WERF_KUBE_CONTEXT: dev
        WERF_LOG_VERBOSE: "on"
        WERF_NAMESPACE: "werfio-test"
      if: contains(github.event.pull_request.labels.*.name, 'test guides')

    - name: Deploy to production
      uses: werf/actions/converge@v1.2
      with:
        env: production
      env:
        WERF_LOG_VERBOSE: "on"
        WERF_KUBE_CONTEXT: prod
        WERF_NAMESPACE: "werfio-production"
      if: github.ref == 'refs/heads/master'
