name: Review guides on stage

on:
  pull_request:
    types: [labeled]
  
jobs:
  unlabel:
    name: Unlabel and deploy to stage
    if: github.event_name == 'pull_request' && github.event.label.name == 'review'
    runs-on: ubuntu-latest
    steps:
    - name: Label taking off
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: '${{ github.event.label.name }}' 
          })
    - name: Deploy to stage
      run: |
        curl -X POST \
             -F "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
             -F "ref=master" \
             -F "variables[review_guide_sha]=${{ github.event.pull_request.head.sha }}" \
             ${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
