name: Deploy to staging

on:
  push:
    branches:
      - staging
env:
  WERF_REPO: "ghcr.io/${{ github.repository_owner }}/werfio-guides"
  WERF_STAGES_STORAGE: "ghcr.io/werf/werfio-guides-stages"

jobs:
  converge:
    name: Deploy guides to staging
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Deploy to stage
      uses: werf/actions/converge@v1.2
      with:
        env: stage
      env:
        WERF_LOG_VERBOSE: "on"
        WERF_KUBE_CONTEXT: stage
        WERF_NAMESPACE: "werfio-stage"